name: req
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pipreqs
        run: |
          pip install pipreqs

      - name: Generate requirements.txt
        run: |
          pipreqs $GITHUB_WORKSPACE --force

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
        
          if [ -f requirements.txt ]; then
            echo "requirements.txt already exists."
          else
            git add requirements.txt
            git commit -m "Add requirements.txt"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
